CREATE TABLE IF NOT EXISTS workflow_marketplace_plugin_probe (
    id BIGINT NOT NULL AUTO_INCREMENT,
    source VARCHAR(16) NOT NULL,
    catalog_external_key VARCHAR(255) NOT NULL,
    package_key VARCHAR(255) NOT NULL,
    package_version VARCHAR(64) NOT NULL,
    package_fingerprint CHAR(64) NULL,
    probe_status VARCHAR(24) NOT NULL DEFAULT 'QUEUED',
    compatibility_status VARCHAR(24) NOT NULL DEFAULT 'PROBING',
    compatibility_reason VARCHAR(500) NOT NULL DEFAULT '',
    result_json LONGTEXT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    next_attempt_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    lease_owner VARCHAR(120) NULL,
    lease_expires_at DATETIME(6) NULL,
    last_accessed_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    probed_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT uk_workflow_marketplace_plugin_probe UNIQUE (source, package_key, package_version),
    INDEX idx_workflow_marketplace_probe_queue (probe_status, next_attempt_at, lease_expires_at),
    INDEX idx_workflow_marketplace_probe_retention (last_accessed_at, probe_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
