CREATE TABLE IF NOT EXISTS automation_api_trigger_config (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(120) NOT NULL,
    description VARCHAR(500) NOT NULL DEFAULT '',
    http_method VARCHAR(10) NOT NULL DEFAULT 'GET',
    url TEXT NOT NULL,
    headers_encrypted MEDIUMTEXT NOT NULL,
    query_params MEDIUMTEXT NOT NULL,
    request_body_encrypted MEDIUMTEXT NOT NULL,
    content_type VARCHAR(120) NOT NULL DEFAULT 'application/json',
    cron_expression VARCHAR(80) NULL,
    timeout_seconds INT NOT NULL DEFAULT 30,
    enabled BIT(1) NOT NULL DEFAULT b'1',
    voided BIT(1) NOT NULL DEFAULT b'0',
    auth_enabled BIT(1) NOT NULL DEFAULT b'0',
    auth_url TEXT NOT NULL,
    auth_method VARCHAR(10) NOT NULL DEFAULT 'POST',
    auth_body_encrypted MEDIUMTEXT NOT NULL,
    auth_content_type VARCHAR(120) NOT NULL DEFAULT 'application/json',
    auth_token_path VARCHAR(200) NOT NULL DEFAULT 'data.token',
    auth_token_header VARCHAR(120) NOT NULL DEFAULT 'Authorization',
    auth_token_prefix VARCHAR(40) NOT NULL DEFAULT 'Bearer ',
    owner_user_id BIGINT NOT NULL,
    last_trigger_at DATETIME(6) NULL,
    last_status VARCHAR(20) NULL,
    last_result MEDIUMTEXT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    INDEX idx_api_trigger_enabled (enabled, voided)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS automation_api_trigger_log (
    id BIGINT NOT NULL AUTO_INCREMENT,
    config_id BIGINT NOT NULL,
    trace_id VARCHAR(32) NULL,
    trigger_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    http_status INT NULL,
    duration_ms BIGINT NULL,
    response_summary MEDIUMTEXT NULL,
    error_message MEDIUMTEXT NULL,
    triggered_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_api_trigger_log_config FOREIGN KEY (config_id) REFERENCES automation_api_trigger_config(id),
    INDEX idx_api_trigger_log_config (config_id, triggered_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
