<template><div class="panel"><div class="section-head"><div><h2>菜单管理</h2><p>维护目录、页面路由和按钮权限。</p></div><el-button v-if="auth.hasPermission('system:menu:create')" type="primary" @click="open()">新增菜单</el-button></div>
<el-table :data="treeRows" row-key="id" default-expand-all><el-table-column prop="name" label="名称"/><el-table-column prop="type" label="类型" width="100"/><el-table-column prop="path" label="路由"/><el-table-column prop="permission" label="权限编码"/><el-table-column label="操作" width="210"><template #default="s"><el-button v-if="auth.hasPermission('system:menu:create')" link @click="open(null,s.row.id)">新增下级</el-button><el-button v-if="auth.hasPermission('system:menu:update')" link type="primary" @click="open(s.row)">编辑</el-button><el-button v-if="auth.hasPermission('system:menu:delete')" link type="danger" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table>
<el-dialog v-model="visible" :title="form.id?'编辑菜单':'新增菜单'" width="620px"><el-form label-width="90px"><el-form-item label="上级"><el-select v-model="form.parentId" clearable><el-option v-for="item in rows" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="类型"><el-radio-group v-model="form.type"><el-radio-button value="CATALOG">目录</el-radio-button><el-radio-button value="MENU">菜单</el-radio-button><el-radio-button value="BUTTON">按钮</el-radio-button></el-radio-group></el-form-item><el-form-item label="路由"><el-input v-model="form.path"/></el-form-item><el-form-item label="组件"><el-input v-model="form.component"/></el-form-item><el-form-item label="图标"><el-input v-model="form.icon"/></el-form-item><el-form-item label="权限编码"><el-input v-model="form.permission"/></el-form-item><el-form-item label="排序"><el-input-number v-model="form.sortOrder"/></el-form-item><el-form-item label="显示"><el-switch v-model="form.visible"/></el-form-item><el-form-item label="启用"><el-switch v-model="form.enabled"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
<script setup>
import { computed,onMounted,reactive,ref } from 'vue';import { ElMessage,ElMessageBox } from 'element-plus';import http from '../api/http';import { useAuthStore } from '../stores/auth';import { buildTree } from '../utils/tree'
const auth=useAuthStore(),rows=ref([]),visible=ref(false),treeRows=computed(()=>buildTree(rows.value));const empty=parentId=>({id:null,parentId:parentId||null,name:'',type:'MENU',path:'',component:'',icon:'',permission:'',sortOrder:0,visible:true,enabled:true});const form=reactive(empty())
async function load(){rows.value=(await http.get('/system/menus')).data}
/** 打开菜单编辑窗口。 */ function open(row,parentId){Object.assign(form,row?{...row}:empty(parentId));visible.value=true}
/** 保存菜单节点。 */ async function save(){try{form.id?await http.put(`/system/menus/${form.id}`,form):await http.post('/system/menus',form);visible.value=false;await load();ElMessage.success('保存成功')}catch(e){ElMessage.error(e.response?.data?.message||'保存失败')}}
/** 删除菜单节点。 */ async function remove(row){await ElMessageBox.confirm(`确认删除菜单「${row.name}」？`,'删除确认',{type:'warning'});await http.delete(`/system/menus/${row.id}`);await load();ElMessage.success('删除成功')}
onMounted(load)
</script>
<!-- 菜单管理页面：维护目录、页面路由和按钮权限。 -->
