<template><div class="panel"><div class="section-head"><div><h2>{{ t('roles.title') }}</h2><p>{{ t('roles.description') }}</p></div><el-button v-if="auth.hasPermission('system:role:create')" type="primary" @click="open()">{{ t('roles.add') }}</el-button></div><el-table :data="rows"><el-table-column prop="code" :label="t('common.code')"/><el-table-column prop="name" :label="t('common.name')"/><el-table-column prop="dataScope" :label="t('roles.scope')"/><el-table-column :label="t('common.status')"><template #default="s">{{s.row.enabled?t('common.enabled'):t('common.disabled')}}</template></el-table-column><el-table-column :label="t('common.operation')" width="150"><template #default="s"><el-button v-if="auth.hasPermission('system:role:update')" link type="primary" @click="open(s.row)">{{ t('common.edit') }}</el-button><el-button v-if="auth.hasPermission('system:role:delete')" link type="danger" @click="remove(s.row)">{{ t('common.delete') }}</el-button></template></el-table-column></el-table><el-pagination v-model:current-page="query.page" :page-size="query.size" :total="total" layout="total, prev, pager, next"/><el-dialog v-model="visible" :title="form.id?t('roles.edit'):t('roles.add')" width="640px"><el-form label-width="100px"><el-form-item :label="t('common.code')"><el-input v-model="form.code"/></el-form-item><el-form-item :label="t('common.name')"><el-input v-model="form.name"/></el-form-item><el-form-item :label="t('common.description')"><el-input v-model="form.description"/></el-form-item><el-form-item :label="t('roles.scope')"><el-select v-model="form.dataScope"><el-option v-for="item in scopes" :key="item.value" :label="item.label" :value="item.value"/></el-select></el-form-item><el-form-item v-if="form.dataScope==='CUSTOM'" :label="t('roles.customDepartments')"><el-select v-model="form.departmentIds" multiple><el-option v-for="item in departments" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item :label="t('roles.permissions')"><el-select v-model="form.menuIds" multiple filterable><el-option v-for="menu in menus" :key="menu.id" :label="`${menu.name}${menu.permission?' · '+menu.permission:''}`" :value="menu.id"/></el-select></el-form-item><el-form-item :label="t('common.enabled')"><el-switch v-model="form.enabled"/></el-form-item></el-form><template #footer><el-button @click="visible=false">{{ t('common.cancel') }}</el-button><el-button type="primary" @click="save">{{ t('common.save') }}</el-button></template></el-dialog></div></template>
<script setup>
import { computed, onMounted, reactive, ref } from 'vue'; import { ElMessage, ElMessageBox } from 'element-plus'; import { useI18n } from 'vue-i18n'; import http from '../api/http'; import { useAuthStore } from '../stores/auth'
const { t } = useI18n(); const auth = useAuthStore(), allRoles = ref([]), menus = ref([]), departments = ref([]), visible = ref(false); const scopes = computed(() => [{value:'ALL',label:t('roles.allData')},{value:'DEPARTMENT',label:t('roles.department')},{value:'DEPARTMENT_AND_CHILDREN',label:t('roles.departmentChildren')},{value:'SELF',label:t('roles.self')},{value:'CUSTOM',label:t('roles.customDepartments')}]); const form = reactive({id:null,code:'',name:'',description:'',dataScope:'ALL',enabled:true,menuIds:[],departmentIds:[]}); const query=reactive({page:1,size:5}); const total=computed(()=>allRoles.value.length); const rows=computed(()=>allRoles.value.slice((query.page-1)*query.size,query.page*query.size))
async function load(){[allRoles.value,menus.value,departments.value]=await Promise.all(['/system/roles','/system/menus','/system/departments'].map(url=>http.get(url).then(r=>r.data)))}
/** 打开角色编辑窗口。 */ function open(row){Object.assign(form,row?{...row,menuIds:[...row.menuIds],departmentIds:[...row.departmentIds]}:{id:null,code:'',name:'',description:'',dataScope:'ALL',enabled:true,menuIds:[],departmentIds:[]});visible.value=true}
/** 保存角色权限。 */ async function save(){try{form.id?await http.put(`/system/roles/${form.id}`,form):await http.post('/system/roles',form);visible.value=false;await load();ElMessage.success(t('common.successSaved'))}catch(e){ElMessage.error(e.response?.data?.message||t('common.saveFailed'))}}
/** 删除未使用角色。 */ async function remove(row){await ElMessageBox.confirm(t('common.confirmDelete',{name:row.name}),t('common.deleteConfirm'),{type:'warning'});await http.delete(`/system/roles/${row.id}`);await load();ElMessage.success(t('common.successDeleted'))} onMounted(load)
</script>
