<template><div class="panel"><div class="section-head"><div><h2>角色管理</h2><p>配置菜单权限和数据可见范围。</p></div><el-button v-if="auth.hasPermission('system:role:create')" type="primary" @click="open()">新增角色</el-button></div>
<el-table :data="rows"><el-table-column prop="code" label="编码"/><el-table-column prop="name" label="名称"/><el-table-column prop="dataScope" label="数据范围"/><el-table-column label="状态"><template #default="s">{{s.row.enabled?'启用':'停用'}}</template></el-table-column><el-table-column label="操作" width="150"><template #default="s"><el-button v-if="auth.hasPermission('system:role:update')" link type="primary" @click="open(s.row)">编辑</el-button><el-button v-if="auth.hasPermission('system:role:delete')" link type="danger" @click="remove(s.row)">删除</el-button></template></el-table-column></el-table>
<el-pagination v-model:current-page="query.page" :page-size="query.size" :total="total" layout="total, prev, pager, next"/>
<el-dialog v-model="visible" :title="form.id?'编辑角色':'新增角色'" width="640px"><el-form label-width="100px"><el-form-item label="编码"><el-input v-model="form.code"/></el-form-item><el-form-item label="名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="说明"><el-input v-model="form.description"/></el-form-item><el-form-item label="数据范围"><el-select v-model="form.dataScope"><el-option v-for="item in scopes" :key="item.value" :label="item.label" :value="item.value"/></el-select></el-form-item><el-form-item v-if="form.dataScope==='CUSTOM'" label="指定部门"><el-select v-model="form.departmentIds" multiple><el-option v-for="item in departments" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item><el-form-item label="权限"><el-select v-model="form.menuIds" multiple filterable><el-option v-for="menu in menus" :key="menu.id" :label="`${menu.name}${menu.permission?' · '+menu.permission:''}`" :value="menu.id"/></el-select></el-form-item><el-form-item label="启用"><el-switch v-model="form.enabled"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div></template>
<script setup>
import { computed, onMounted, reactive, ref } from 'vue';import { ElMessage,ElMessageBox } from 'element-plus';import http from '../api/http';import { useAuthStore } from '../stores/auth'
const auth=useAuthStore(),allRoles=ref([]),menus=ref([]),departments=ref([]),visible=ref(false);const scopes=[{value:'ALL',label:'全部数据'},{value:'DEPARTMENT',label:'本部门'},{value:'DEPARTMENT_AND_CHILDREN',label:'本部门及下级'},{value:'SELF',label:'仅本人'},{value:'CUSTOM',label:'指定部门'}];const form=reactive({id:null,code:'',name:'',description:'',dataScope:'ALL',enabled:true,menuIds:[],departmentIds:[]})
const query=reactive({page:1,size:10});const total=computed(()=>allRoles.value.length);const rows=computed(()=>allRoles.value.slice((query.page-1)*query.size,query.page*query.size))
async function load(){[allRoles.value,menus.value,departments.value]=await Promise.all(['/system/roles','/system/menus','/system/departments'].map(url=>http.get(url).then(r=>r.data)))}
/** 打开角色编辑窗口。 */ function open(row){Object.assign(form,row?{...row,menuIds:[...row.menuIds],departmentIds:[...row.departmentIds]}:{id:null,code:'',name:'',description:'',dataScope:'ALL',enabled:true,menuIds:[],departmentIds:[]});visible.value=true}
/** 保存角色权限。 */ async function save(){try{form.id?await http.put(`/system/roles/${form.id}`,form):await http.post('/system/roles',form);visible.value=false;await load();ElMessage.success('保存成功')}catch(e){ElMessage.error(e.response?.data?.message||'保存失败')}}
/** 删除未使用角色。 */ async function remove(row){await ElMessageBox.confirm(`确认删除角色「${row.name}」？`,'删除确认',{type:'warning'});await http.delete(`/system/roles/${row.id}`);await load();ElMessage.success('删除成功')}
onMounted(load)
</script>
